# Generated by Django 3.0.5 on 2020-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='username'),
        ),
    ]
