# Generated by Django 3.0.5 on 2020-05-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='username')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='date started')),
                ('content', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
